[Icon Theme]
Name=RetroismIcons
Comment=Icon theme for the Retroism linux desktop.
Inherits=Adwaita,hicolor
Directories=actions/24,apps/16,apps/24,apps/32,apps/48,apps/128,apps/256,categories/16,categories/32,devices/16,devices/32,mimes/16,mimes/32,places/16,places/32

[actions/24]
Size=24
Context=Applications
Type=Fixed

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/24]
Size=24
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Fixed

[apps/128]
Size=128
Context=Applications
Type=Fixed

[apps/256]
Size=256
Context=Applications
Type=Fixed

[categories/16]
Size=16
Context=Applications
Type=Fixed

[categories/32]
Size=32
Context=Applications
Type=Fixed

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[mimes/16]
Size=16
Context=Applications
Type=Fixed

[mimes/32]
Size=32
Context=Applications
Type=Fixed

[places/16]
Size=16
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed
